/*
 * Este arquivo foi gerado automaticamente pela xDevStudio e contem diversas
 * diretrivas de processamento indicando detalhes do compilador/linker usado
 * para gerar o arquivo final deste projeto.
 *
 * 16/11/2018 - 12:42:55
 */

#ifndef _XINC_XHB_123_21944
   #define _XINC_XHB_123_21944

   #define XDEV_TITLE   "xDev Studio"
   #define XDEV_VER     "0.72"
   #define XDEV_RELEASE "Julho/2008"
   #define XDEV_PRESET  "xHB build 1.2.3 (SimpLex) & FW 17.09"

   #define xHB 
#endif
